# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

require 'httparty'

default_platform :android

platform :android do

  UPDATE_TYPES = [:major, :minor, :patch]

  desc "Start release candidate"
  lane :start_release_candidate do |options|

    update_type = nil
    if UI.interactive?
        update_type = UI.select "What's the update type?:", UPDATE_TYPES
    else
        update_type = options[:update_type].to_sym
    end

    begin
      puts "Printing update type:"
      puts update_type

    rescue => ex
      UI.error ex
    end

  end

  desc "Start hotfix"
  lane :start_hotfix do

    begin
      puts "Starting some hotfix!"

      rescue => ex
        UI.error ex
      end
    end

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
